### ISSUE TITLE
Version tag not updated

### ISSUE THREAD

**Issue by Berserker66** [Ijwu/Enemizer#12]
The 7.0 release still reports 6.4.0 in EnemizerCLI.Core.deps.json -> "EnemizerLibrary": "6.4.0" (Which AP uses to check version)
As well as in EnemizerVersion.json

This for now blocks AP from making use the now accepted romnames, as it can't ensure that the user updated.

**Comment by Ijwu** [comment]
ugh

**Comment by Ijwu** [comment]
7.0.1 released to solve this. Thanks.
